services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: site_laravel_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:8080"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
